sudo: false
dist: trusty
language: node_js
node_js:
  - "6.9"

addons:
    code_climate:
        repo_token: ec507f052b354c2a3cb1e5d3fda0ec9b36e3b257c5a08ddd63b2f1e156487773
    apt:
      sources:
       - google-chrome
      packages:
       - google-chrome-stable

before_script:
  - npm install -g @angular/cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ng test --watch false
  - ng build --prod

notifications:
  email:
    on_success: never # default: change


