sudo: false
dist: trusty
language: node_js
node_js:
  - "6.9"

addons:
    apt:
      sources:
       - google-chrome
      packages:
       - google-chrome-stable

before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ng test --watch false
  - ng build --prod

notifications:
  email:
    on_success: never # default: change

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
