language: node_js
node_js:
  - "6.9"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ng build --prod
